### ISSUE TITLE
admin:admin not works out of the box

### ISSUE THREAD

**Issue by didntchooseaname** [CTF-Cafe/CTF_Cafe#111]
Hello, admin:admin not works out of the box (8 characters needed for pass) and i didnt figured out how to set an user admin due to lack of informations.

Thank you.

**Comment by RaxoCoding** [comment]
Hey @didntchooseaname the default admin user password is logged in the logs of the backend when first launched if no user exists in the DB. I know this is not documented as of now. If you already started the backend, just delete/reset the DB and launching the backend should log the admin:pass combo in the console. Sorry for that being unclear!
