### ISSUE TITLE
Require user to either delete admin:admin or change the password

### ISSUE THREAD

**Issue by hKQwHW** [CTF-Cafe/CTF_Cafe#17]
We don't want an administrator account with the default password set when an actual CTF is running, that isn't great for security. We should either a) require the user to delete the admin:admin account, or b) change its password.

**Comment by Gomez0015** [comment]
Alright ill add a thing to require admin to change password before anyone else can register, that should be enough.

**Comment by hKQwHW** [comment]
Was this ever done?

**Comment by Gomez0015** [comment]
Nope was busy will do it now
