### ISSUE TITLE
Hardcoded Tags

### ISSUE THREAD

**Issue by david-prv** [CTF-Cafe/CTF_Cafe#6]
See here: [Reference](https://github.com/CTF-Cafe/CTF_Cafe/blob/85ab018213f4feda82f8d8891aac0168f25c50f7/discordBot/commands/scoreboard.js#L67)

I think it would be a nice thing to add this to some kind of configuration file.
Thanks in advance.

**Comment by Gomez0015** [comment]
Yes will definitely update to the actual CTF Name stored in the DB

**Comment by hKQwHW** [comment]
I might make a PR to do this soon once we fix the problem with localhost instantly expiring sessions

**Comment by hKQwHW** [comment]
> I think it would be a nice thing to add this to some kind of configuration file.

I think he's asking for this to be able to be configured:
```js
            .setFooter({ text: 'Raxo#0468' });
```

**Comment by david-prv** [comment]
Yea @hKQwHW is right. I'm asking for dynamic configuration of the information used in embedded messages in general.
Another [reference](https://github.com/CTF-Cafe/CTF_Cafe/blob/85ab018213f4feda82f8d8891aac0168f25c50f7/discordBot/commands/scoreboard.js#L65), same embedded Message.

**Comment by hKQwHW** [comment]
I'll look into adding this

**Comment by Gomez0015** [comment]
Fixed ✅
