### ISSUE TITLE
Password security

### ISSUE THREAD

**Issue by hKQwHW** [CTF-Cafe/CTF_Cafe#9]
The user accounts are a bit insecure. I would suggest that:
- [ ] The default admin password be randomized
- [x] We use bcrypt hashes

I'll mark those as complete when/if they get done. Feel free to share your thoughts.

**Comment by Gomez0015** [comment]
For the admin password, it doesn't matter its just a temporary account to login, they should delete it right after setup when they have created another account

**Comment by hKQwHW** [comment]
> For the admin password, it doesn't matter its just a temporary account to login, they should delete it right after setup when they have created another account

Well, I feel that we should require them to do that then. See: https://en.wikipedia.org/wiki/Secure_by_default

**Comment by hKQwHW** [comment]
Moving to #17
